# Sets default values for kla. These are used when not provided via flags
[default]
# sets the --env flag by default. This value is actually a file since the `switch`
# subcommand can change this value to switch contexts.
environment = ".default-environment"

[environment.github]
url = "https://api.github.com/"
short_description = "Github api"

[environment.bored]
url = "https://www.boredapi.com/api"
short_description = "An API giving you ideas for when you are bored"

[environment.poetry]
url = "https://poetrydb.org/"
short_description = "Poetry by authors"
