short_description = "An example of a template. This will show up when running help on the `run` command"
description = """
    This is a much longer description, and something that should take up a considerable amount of space.
    This will show when running `--help` on this specific command, so make sure you really describe how
    to use this command for the user to create the best experience for them.
"""
body = """
This was your argument: {{ argument }}
"""
uri = "/"

[[arg]]
name = "argument"
short = 'a'
short_aliases = ['b', 'c']
long = "argument-flag"
aliases = ["arg", "awesome-arg"]
help = "This is a short description"
long_help = """
    This is a longer help text that can be displayed sometimes, so here I am going to go on and on and on for a while to make this as long as possible, and apparently I am going to use some smaller words that make the words feel cheap and choppy. Oh well.
"""
next_line_help = true
required = true
default_value = "argument value"
env = "KLA_ARG_VAL"
